In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 17.1 MB 2.6 MB/s eta 0:00:01
  distutils: /home/moore/.local/lib/python3.9/site-packages
  sysconfig: /home/moore/.local/lib64/python3.9/site-packages
  user = True
  home = None
  root = None
  prefix = None


In [2]:
import numpy as np

In [3]:
A = [[6, 7],
     [8, 0]]

In [5]:
print(np.array(A)[0, 0])

6


In [6]:
A = 5

In [7]:
B = [[6, 7],
     [8, 9]]

In [9]:
print(np.dot(A, B))

[[30 35]
 [40 45]]


In [10]:
A = [[6, 7],
     [8, 9]]

B = [[1, 3],
     [5, 7]]

print(np.dot(A, B))
print(np.dot(B, A))

[[41 67]
 [53 87]]
[[30 34]
 [86 98]]


In [11]:
import numpy as np

A = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])
B = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])

print(np.multiply(A,B))

[[ 1  6 15 28 45]
 [10 16 18 16 10]]


In [14]:
import numpy as np

A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
B = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

print(np.multiply(A[ 0,:], B[ 1,: ]))
print(np.multiply(A[ 1,:], B[ 0,:]))


[ 16  34  54  76 100]
[ 66  84 104 126 150]
